DIALOG DLG_COLLADAEXPORTPLUSSETTINGS
{
	NAME COLLADAEXPORT_DIALOG_TITLE;
	SCALE_H; SCALE_V;

	GROUP 
	{
		COLUMNS 1;
		BORDERSIZE 8, 8, 8, 8;
		SCALE_H; SCALE_V;
	
		GROUP
		{
			COLUMNS 1;
			SCALE_H; SCALE_V;

			CHECKBOX COLLADAEXPORT_ANIMATION { NAME COLLADAEXPORT_ANIMATION; }

			CHECKBOX COLLADAEXPORT_EMPTY_NULLS { NAME COLLADAEXPORT_EMPTY_NULLS; }

			CHECKBOX COLLADAEXPORT_REMOVE_XREFS { NAME COLLADAEXPORT_REMOVE_XREFS; }

			CHECKBOX COLLADAEXPORT_REMOVE_TEXTURE_TAGS { NAME COLLADAEXPORT_REMOVE_TEXTURE_TAGS; }
		}

		DLGGROUP { OK; CANCEL; }
	}
}