#ifndef _DLG_COLLADAEXPORTPLUSSETTINGS_H_
#define _DLG_COLLADAEXPORTPLUSSETTINGS_H_

enum
{	
	DLG_COLLADAEXPORTPLUSSETTINGS = 10000,
    COLLADAEXPORT_ANIMATION = 1000,
    COLLADAEXPORT_EMPTY_NULLS = 1001,
    COLLADAEXPORT_REMOVE_XREFS = 1002,
    COLLADAEXPORT_REMOVE_TEXTURE_TAGS = 1003
}

#endif