#ifndef _ColladaExportSettings_H_
#define _ColladaExportSettings_H_

enum
{
    COLLADA_EXPORT_SETTINGS_ENABLE_EXPORT = 1017,
    COLLADA_EXPORT_SETTINGS_EXTERNAL_TEXTURE = 1018,
    COLLADA_EXPORT_SETTINGS_TRANSFER_COLOR = 1019,
    COLLADA_EXPORT_SETTINGS_USE_TEXTURE_ALPHA = 1020,
    COLLADA_EXPORT_SETTINGS_CUSTOM_DATA = 1021,
    COLLADA_EXPORT_SETTINGS_MERGE_CHILDREN = 1022
}

#endif