#ifndef _ColladaExportSettings_H_
#define _ColladaExportSettings_H_

enum
{
    COLLADA_EXPORT_SETTINGS_ENABLE_EXPORT = 1017,
    COLLADA_EXPORT_SETTINGS_EXTERNAL_TEXTURE = 1018,
    COLLADA_EXPORT_SETTINGS_TEXTURETYPE = 1019,
	COLLADA_EXPORT_SETTINGS_TEXTURETYPE_SVG = 1020,
	COLLADA_EXPORT_SETTINGS_TEXTURETYPE_BITMAP = 1021,
}

#endif