CONTAINER ColladaExportSettings
{
	NAME ColladaExportSettings;
    INCLUDE Tbase;
    
    GROUP ID_TAGPROPERTIES
	{
		GROUP 
		{
			BOOL COLLADA_EXPORT_SETTINGS_ENABLE_EXPORT { ANIM OFF; }
			FILENAME COLLADA_EXPORT_SETTINGS_EXTERNAL_TEXTURE { ANIM OFF; }
			BOOL COLLADA_EXPORT_SETTINGS_USE_TEXTURE_ALPHA { ANIM OFF; }
			BOOL COLLADA_EXPORT_SETTINGS_TRANSFER_COLOR { ANIM OFF; }

			SEPARATOR { LINE; }

			STRING COLLADA_EXPORT_SETTINGS_CUSTOM_DATA { ANIM OFF; }
		}

		STATICTEXT 
		{ 
			ANIM OFF;
			NAME COLLADA_EXPORT_SETTINGS_CUSTOM_DATA_HELP; 
			PARENTID COLLADA_EXPORT_SETTINGS_CUSTOM_DATA;
		}
	}
}