enum
{
	IDS_COLLADAEXPORTSETTINGS = 10000,
		
	COLLADA_EXPORT_SETTINGS_EXTERNAL_TEXTURE,
	COLLADA_EXPORT_SETTINGS_TEXTURETYPE,
	COLLADA_EXPORT_SETTINGS_TEXTURETYPE_SVG,
	COLLADA_EXPORT_SETTINGS_TEXTURETYPE_BITMAP,
	
    _DUMMY_ELEMENT_
};